export const baseUrl = 'https://backend.yetublog.com/'
export const baseUrlImage = 'https://yetublog.com/'
// export const supabaseUrl = 'https://albhcerevbneckiahepo.supabase.co'
// export const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYmhjZXJldmJuZWNraWFoZXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDIwNDk4NDAsImV4cCI6MjAxNzYyNTg0MH0.1eN0468G03nh4QM0PbDPgJ7-6vbAiM6KiM5rnfPSWyU'
// export const supabaseAPIkey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxcWF2ZG9pcXFhd3FiYXFyZ3RzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMTgyODI0OSwiZXhwIjoyMDE3NDA0MjQ5fQ.2AcPppLXtWxfpITM-26SGAPcVpgJUsBlgFaWsrivX40'